# Site settings
title: arxscio
email: arxscio@pm.me
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/arxscio" # the subpath of your site, e.g. /blog/
url: "https://zehmaria.github.io" # the base hostname & protocol for your site
twitter_username: arxscio
github_username:  zehmaria

include: ["_pages", "_novels"]
permalink: ":path/:slug"

collections_dir: novels
collections:
  uncrowned:
    output: true
    permalink: "/novels/:collection/:slug"
  heavensoddity:
    output: true
    permalink: "/novels/:collection/:slug"

feed:
  collections:
    - heavensoddity
    - uncrowned

defaults:
  -
    scope:
      path: ""
      type: "heavensoddity"
    values:
      layout: "chapter"
      backlink: /novels/heavensoddity
  -
    scope:
      path: ""
      type: "uncrowned"
    values:
      layout: "chapter"
      backlink: /novels/uncrowned
    
plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - LICENSE.txt
  - README.md
